# Generated by Django 5.2.8 on 2025-11-08 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_add_favourites'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='company',
            new_name='common_comp_owner_i_7ac174_idx',
            old_name='common_company_owner_idx',
        ),
        migrations.RenameIndex(
            model_name='favouriterestaurant',
            new_name='common_favo_user_id_0924f6_idx',
            old_name='common_fav_user_rest_idx',
        ),
        migrations.RenameIndex(
            model_name='favouriterestaurant',
            new_name='common_favo_user_id_998fb8_idx',
            old_name='common_fav_rest_user_idx',
        ),
        migrations.RenameIndex(
            model_name='favouriterestaurant',
            new_name='common_favo_restaur_bc82f6_idx',
            old_name='common_fav_rest_rest_idx',
        ),
        migrations.RenameIndex(
            model_name='favouriterestaurantitem',
            new_name='common_favo_user_id_fdffe3_idx',
            old_name='common_fav_user_menu_idx',
        ),
        migrations.RenameIndex(
            model_name='favouriterestaurantitem',
            new_name='common_favo_user_id_c0c480_idx',
            old_name='common_fav_item_user_idx',
        ),
        migrations.RenameIndex(
            model_name='favouriterestaurantitem',
            new_name='common_favo_menu_it_a7dfaf_idx',
            old_name='common_fav_item_menu_idx',
        ),
    ]
